### ISSUE TITLE
Unable to access the internet

### ISSUE THREAD

**Issue by ful09003** [riptidewave93/DO-Bootstrap#3]
'Lo!

Dropping this here so that you don't forget. Running DO-Bootstrap without IPv6 fails, enabling IPv6 works.

Also, "also gives me an excuse to update this to latest buildroot and kernel" ;^)

**Comment by riptidewave93** [comment]
Kernel and Buildroot base updated. Re-working logic to parse the metadata JSON vs a ton of wget calls.

**Comment by riptidewave93** [comment]
Fixed in master.
